apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: efx-mw-fxbo
  annotations:
    run.googleapis.com/launch-stage: BETA
    run.googleapis.com/ingress: internal-and-cloud-load-balancing
  labels:
    cloud.googleapis.com/location: europe-west1
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "5"
        autoscaling.knative.dev/minScale: "1"
        run.googleapis.com/network-interfaces: '[{"network":"projects/prj-empirefx-prd-net/global/networks/svpc-empirefx-prd-net","subnetwork":"projects/prj-empirefx-prd-net/regions/europe-west1/subnetworks/sb-svpc-empirefx-prd-net-europe-west1-empirefx"}]'
        run.googleapis.com/vpc-access-egress: private-ranges-only
        run.googleapis.com/cloudsql-instances: prj-empirefx-eng-prd:europe-west1:empire-prod
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 8
      serviceAccountName: sa-eng-prd-cloudrun@prj-empirefx-eng-prd.iam.gserviceaccount.com
      containers:
      - name: efx-mw-fxbo
        image: efx-mw-fxbo
        ports:
        - containerPort:  8081
        env:
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8081

            




