apiVersion: v1
kind: Service
metadata:
  name: efx-mw-fxbo-service
  namespace: backend-services
spec:
  type: NodePort
  selector:
    app: efx-mw-fxbo
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
    - name: metrics
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30081

