name: Build JAR and Docker Image

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean install

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
             
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.efx-mw-fxbo-dev-buildx-cache
        key: ${{ runner.os }}-single-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-single-buildx
          
    - name: Pull secrets
      run: |
          echo ${{ secrets.DIGITALOCEAN_REGISTRY_USERNAME }}
          echo ${{ secrets.DIGITALOCEAN_REGISTRY_PASSWORD }}
          
    - name: Log in to DigitalOcean Container Registry
      uses: docker/login-action@v3
      with:
        registry: registry.digitalocean.com
        username: ${{ secrets.DIGITALOCEAN_REGISTRY_USERNAME }}
        password: ${{ secrets.DIGITALOCEAN_REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      env:
          DOCKER_REGISTRY: registry.digitalocean.com
          DOCKER_REPOSITORY: efx-registry
          IMAGE_NAME: efx-mw-fxbo-dev
      run: |
          docker buildx build \
            --push \
            --tag ${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}/${IMAGE_NAME}:${{ github.sha }} \
            --tag ${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}/${IMAGE_NAME}:latest \
            .


